import {integrations} from './integrations.js';
import {operations} from './operations.js';
import express from 'express';import mongoose from 'mongoose';import bcrypt from 'bcrypt';import cookieParser from 'cookie-parser';import cors from 'cors';import helmet from 'helmet';import rateLimit from 'express-rate-limit';import {randomBytes,createHmac} from 'node:crypto';import {z} from 'zod';import PDFDocument from 'pdfkit';import {User,Session,Venue,Package,Booking,Reservation,Payment,Ledger,Audit,Notification,Inquiry,Consultation,Task,Expense} from './models.js';import {price,transitions} from './pricing.js';
const env=z.object({MONGODB_URI:z.string().min(1),SESSION_SECRET:z.string().min(32),CLIENT_ORIGIN:z.url(),PORT:z.coerce.number().default(4000)}).parse(process.env);const app=express();if(process.env.NODE_ENV==='production')app.set('trust proxy',1);app.disable('x-powered-by');app.use(helmet());app.use(cors({origin:env.CLIENT_ORIGIN,credentials:true}));app.use(express.json({limit:'256kb'}));app.use(cookieParser());app.use('/api',rateLimit({windowMs:60000,limit:180}));
const hash=(s:string)=>createHmac('sha256',env.SESSION_SECRET).update(s).digest('hex');const fail=(message:string,status=400)=>Object.assign(new Error(message),{status});
app.use(async(req:any,res,next)=>{try{if(req.cookies.rv){const session=await Session.findOne({token:hash(req.cookies.rv),expires:{$gt:new Date()}}).populate('user');if(session){req.user=session.user;req.session=session;}}if(!['GET','HEAD','OPTIONS'].includes(req.method)){if(req.headers.origin!==env.CLIENT_ORIGIN)throw fail('Origin rejected',403);if(req.user&&req.headers['x-csrf-token']!==req.session.csrf)throw fail('Security token missing; refresh and try again',403);}next();}catch(e){next(e);}});
function auth(req:any,_res:any,next:any){if(!req.user)return next(fail('Please sign in',401));next();}function roles(...allowed:string[]){return(req:any,_res:any,next:any)=>{if(!req.user||!allowed.includes(req.user.role))return next(fail('Access denied',403));next();};}
const admins=roles('Super Admin','Branch Admin');const finance=roles('Super Admin');const id=z.string().regex(/^[a-f0-9]{24}$/i);const date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(s=>!isNaN(Date.parse(s))&&new Date(s).toISOString().slice(0,10)===s,'Invalid date');const slot=z.enum(['Lunch','Evening']);
function scope(user:any){if(user.role==='Super Admin')return {};if(user.role==='Customer')return {customer:user._id};if(user.role==='Staff')return {manager:user._id};return {venue:{$in:user.venues}};}
async function ownedBooking(req:any){const b=await Booking.findOne({_id:id.parse(req.params.id),...scope(req.user)});if(!b)throw fail('Booking not found',404);return b;}
async function audit(req:any,action:string,target:string,session?:any){await Audit.create([{actor:req.user._id,action,target}],session?{session}:{});}
app.get('/api/health',(_req,res)=>res.json({data:{database:mongoose.connection.readyState===1?'connected':'offline'}}));
app.get('/api/auth/me',(req:any,res)=>res.json({data:req.user?{user:{_id:req.user._id,name:req.user.name,email:req.user.email,role:req.user.role},csrf:req.session.csrf}:null}));
const credentials=z.object({email:z.email().transform(s=>s.toLowerCase()),password:z.string().min(12).max(128),name:z.string().min(2).max(100).optional()});
async function login(req:any,res:any,user:any){const raw=randomBytes(32).toString('hex'),csrf=randomBytes(32).toString('hex');await Session.create({user:user._id,token:hash(raw),csrf,expires:new Date(Date.now()+86400000)});res.cookie('rv',raw,{httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'lax',maxAge:86400000,path:'/'});res.json({data:{user:{_id:user._id,name:user.name,email:user.email,role:user.role},csrf}});}
const loginLimit=rateLimit({windowMs:900000,limit:15});
app.post('/api/auth/register',loginLimit,async(req,res)=>{const b=credentials.extend({name:z.string().min(2).max(100)}).parse(req.body);if(await User.exists({email:b.email}))throw fail('Registration unavailable for this email');const u=await User.create({...b,password:await bcrypt.hash(b.password,12),role:'Customer'});await login(req,res,u);});
app.post('/api/auth/login',loginLimit,async(req,res)=>{const b=credentials.parse(req.body);const u=await User.findOne({email:b.email}).select('+password');if(!u||!await bcrypt.compare(b.password,u.password))throw fail('Invalid email or password',401);await login(req,res,u);});
app.post('/api/auth/logout',auth,async(req:any,res)=>{await Session.deleteOne({_id:req.session._id});res.clearCookie('rv',{path:'/'});res.json({data:true});});
app.get('/api/venues',async(req,res)=>{const q=z.object({search:z.string().max(100).default(''),guests:z.coerce.number().int().min(0).default(0),city:z.string().max(100).optional(),outdoor:z.enum(['true','false']).optional()}).parse(req.query);const filter:any={archived:false,capacity:{$gte:q.guests}};if(q.search)filter.name={$regex:q.search.replace(/[.*+?^{}()|[\]\\]/g,'\\$&'),$options:'i'};if(q.city)filter.city=q.city;if(q.outdoor)filter.outdoor=q.outdoor==='true';res.json({data:await Venue.find(filter).sort({name:1}).limit(100)});});
app.get('/api/venues/:id',async(req,res)=>{const v=await Venue.findOne({_id:id.parse(req.params.id),archived:false});if(!v)throw fail('Palace not found',404);res.json({data:v});});
app.get('/api/packages',async(_req,res)=>res.json({data:await Package.find({archived:false}).sort({perHead:1})}));
app.get('/api/availability/:id',async(req,res)=>{const month=z.string().regex(/^\d{4}-\d{2}$/).parse(req.query.month);res.json({data:await Reservation.find({venue:id.parse(req.params.id),date:{$gte:month+'-01',$lte:month+'-31'}}).select('date slot maintenance')});});
const bookingInput=z.object({venue:id,package:id,date,slot,event:z.enum(['Barat','Walima','Mehndi','Nikah']),guests:z.number().int().min(1).max(5000),theme:z.enum(['Royal Gold','Ivory Elegance','Enchanted Garden','Crystal Palace','Rose Gold Romance','Mughal Heritage','Midnight Luxury','Modern Minimal Glamour']),notes:z.string().max(2000).default('')});
async function estimate(b:any){const [v,p]=await Promise.all([Venue.findOne({_id:b.venue,archived:false}),Package.findOne({_id:b.package,archived:false})]);if(!v||!p)throw fail('Collection or palace unavailable');if(b.date<new Date().toISOString().slice(0,10))throw fail('Choose a future date');return {...price(v as any,p as any,b.guests),venueName:v.name,date:b.date,slot:b.slot,theme:b.theme};}
app.post('/api/estimate',async(req,res)=>res.json({data:await estimate(bookingInput.parse(req.body))}));
app.post('/api/bookings',roles('Customer'),async(req:any,res)=>{const b=bookingInput.parse(req.body);const snapshot=await estimate(b);let result:any;await mongoose.connection.transaction(async session=>{[result]=await Booking.create([{...b,customer:req.user._id,snapshot}],{session});await Reservation.create([{venue:b.venue,date:b.date,slot:b.slot,booking:result._id}],{session});await Notification.create([{user:req.user._id,message:'Your wedding request has been received. The slot is reserved pending review.'}],{session});await audit(req,'booking.create',String(result._id),session);});res.status(201).json({data:result});});
app.get('/api/bookings',auth,async(req:any,res)=>{const page=z.coerce.number().int().min(1).max(10000).default(1).parse(req.query.page);const records=await Booking.find(scope(req.user)).populate('venue','name').populate('customer','name email').sort({date:1,_id:1}).skip((page-1)*50).limit(50).lean();res.json({data:records.map((b:any)=>{if(!['Customer','Super Admin'].includes(req.user.role)){delete b.paid;b.snapshot={venueName:b.snapshot.venueName};}return b;})});});
app.patch('/api/bookings/:id/status',auth,async(req:any,res)=>{const b=await ownedBooking(req);const {status}=z.object({status:z.string()}).parse(req.body);if(req.user.role==='Customer'&&status!=='Cancelled')throw fail('Access denied',403);if(req.user.role==='Staff')throw fail('Access denied',403);if(!transitions[b.status!]?.includes(status))throw fail('Invalid status transition');if(status==='Confirmed'&&b.paid!<=0)throw fail('Approve an advance before confirming');await mongoose.connection.transaction(async session=>{const updated=await Booking.updateOne({_id:b._id,status:b.status},{$set:{status}},{session});if(!updated.modifiedCount)throw fail('Booking changed; refresh',409);if(status==='Cancelled')await Reservation.deleteOne({booking:b._id},{session});await Notification.create([{user:b.customer,message:'Booking status: '+status}],{session});await audit(req,'booking.status',String(b._id),session);});res.json({data:true});});
app.patch('/api/bookings/:id/plan',roles('Customer'),async(req:any,res)=>{const b=await ownedBooking(req);const input=z.object({checklist:z.array(z.object({title:z.string().max(200),done:z.boolean()})).max(100),guestList:z.array(z.object({name:z.string().min(1).max(100),table:z.string().max(50)})).max(2000),timeline:z.array(z.object({time:z.string().max(30),title:z.string().max(200)})).max(100),notes:z.string().max(2000)}).parse(req.body);await Booking.updateOne({_id:b._id},{$set:input});res.json({data:true});});
app.patch('/api/bookings/:id/manager',admins,async(req:any,res)=>{const b=await ownedBooking(req);const manager=id.parse(req.body.manager);const u=await User.findOne({_id:manager,role:'Hall Manager',venues:b.venue});if(!u)throw fail('Manager must be assigned to this venue');b.manager=u._id;await b.save();await audit(req,'booking.assign',String(b._id));res.json({data:true});});
app.post('/api/bookings/:id/payments',roles('Customer'),async(req:any,res)=>{const b=await ownedBooking(req);if(b.status==='Cancelled')throw fail('Booking is cancelled');const input=z.object({amount:z.number().int().positive().max(b.snapshot.total-b.paid!),method:z.enum(['Cash','Bank Transfer','Easypaisa','JazzCash']),reference:z.string().min(3).max(200),key:z.string().uuid()}).parse(req.body);const existing=await Payment.findOne({key:input.key});if(existing){if(String(existing.customer)!==String(req.user._id))throw fail('Idempotency key unavailable',409);return res.json({data:existing});}res.status(201).json({data:await Payment.create({...input,booking:b._id,customer:req.user._id})});});
app.get('/api/payments',auth,async(req:any,res)=>{if(!['Customer','Super Admin'].includes(req.user.role))throw fail('Financial access denied',403);res.json({data:await Payment.find(req.user.role==='Customer'?{customer:req.user._id}:{}).sort({createdAt:-1}).limit(100)});});
app.post('/api/payments/:id/approve',finance,async(req:any,res)=>{await mongoose.connection.transaction(async session=>{const p=await Payment.findOneAndUpdate({_id:id.parse(req.params.id),status:'Pending'},{$set:{status:'Approved',approvedBy:req.user._id}},{session,new:true});if(!p){if(await Payment.exists({_id:req.params.id,status:'Approved'}).session(session))return;throw fail('Payment not found',404);}const b=await Booking.findOneAndUpdate({_id:p.booking,status:{$ne:'Cancelled'},$expr:{$lte:[{$add:['$paid',p.amount]},'$snapshot.total']}},{$inc:{paid:p.amount}},{session,new:true});if(!b)throw fail('Payment exceeds balance or booking cancelled');await Ledger.create([{booking:p.booking,amount:p.amount,type:'Payment',key:'payment:'+p._id,actor:req.user._id,reference:p.reference}],{session});await Notification.create([{user:b.customer,message:'Payment approved. Thank you.'}],{session});await audit(req,'payment.approve',String(p._id),session);});res.json({data:true});});
app.post('/api/bookings/:id/refund',finance,async(req:any,res)=>{const b=await ownedBooking(req);const input=z.object({amount:z.number().int().positive(),reference:z.string().min(3).max(200),key:z.string().uuid()}).parse(req.body);await mongoose.connection.transaction(async session=>{const existing=await Ledger.findOne({key:'refund:'+input.key}).session(session);if(existing){if(String(existing.booking)!==String(b._id))throw fail('Idempotency conflict',409);return;}const updated=await Booking.findOneAndUpdate({_id:b._id,paid:{$gte:input.amount}},{$inc:{paid:-input.amount}},{session});if(!updated)throw fail('Refund exceeds approved payments');await Ledger.create([{...input,booking:b._id,type:'Refund',amount:-input.amount,key:'refund:'+input.key,actor:req.user._id}],{session});await audit(req,'payment.refund',String(b._id),session);});res.json({data:true});});
app.get('/api/ledger',finance,async(_req,res)=>res.json({data:await Ledger.find().sort({createdAt:-1}).limit(200)}));
app.get('/api/bookings/:id/invoice',auth,async(req:any,res)=>{const b=await ownedBooking(req);if(!['Customer','Super Admin'].includes(req.user.role))throw fail('Financial access denied',403);const u=await User.findById(b.customer);const doc=new PDFDocument({size:'A4',margin:48});res.setHeader('Content-Type','application/pdf');res.setHeader('Content-Disposition','attachment; filename="RoyalVows-'+b._id+'.pdf"');doc.pipe(res);doc.fillColor('#A78042').fontSize(32).text('ROYALVOWS');doc.fillColor('#090B10').fontSize(12).text('Every Love Story Deserves a Palace').moveDown(2);doc.fontSize(20).text('Booking invoice').fontSize(10).text('Reference: RV-'+b._id).text('Customer: '+u?.name).text('Palace: '+b.snapshot.venueName).text('Event: '+b.event+' | '+b.date+' | '+b.slot).text('Guests: '+b.guests).moveDown();for(const key of ['rental','catering','decor','discount','tax','total'])doc.fontSize(12).text(key.toUpperCase()+': PKR '+(b.snapshot[key]/100).toFixed(2));doc.moveDown().text('Approved payments: PKR '+(b.paid!/100).toFixed(2)).text('Balance: PKR '+((b.snapshot.total-b.paid!)/100).toFixed(2)).text('Status: '+b.status).moveDown().fontSize(9).text('Demo venue quotation. Confirm legal venue identity and contract terms before production use. Refunds are recorded separately.');doc.end();});
app.post('/api/inquiries',async(req:any,res)=>{const b=z.object({name:z.string().min(2).max(100),email:z.email(),message:z.string().min(10).max(2000)}).parse(req.body);res.status(201).json({data:await Inquiry.create({...b,customer:req.user?._id})});});
app.get('/api/inquiries',auth,async(req:any,res)=>{if(!['Customer','Super Admin'].includes(req.user.role))throw fail('Access denied',403);res.json({data:await Inquiry.find(req.user.role==='Customer'?{customer:req.user._id}:{}).sort({createdAt:-1}).limit(100)});});
app.post('/api/consultations',roles('Customer'),async(req:any,res)=>{const b=z.object({date,slot:z.enum(['10:00','12:00','15:00','17:00']),notes:z.string().max(1000)}).parse(req.body);if(b.date<new Date().toISOString().slice(0,10))throw fail('Choose a future date');res.status(201).json({data:await Consultation.create({...b,customer:req.user._id})});});
app.get('/api/consultations',auth,async(req:any,res)=>{if(!['Customer','Super Admin'].includes(req.user.role))throw fail('Access denied',403);res.json({data:await Consultation.find(req.user.role==='Customer'?{customer:req.user._id}:{}).sort({date:1}).limit(100)});});
app.patch('/api/consultations/:id',finance,async(req,res)=>{const status=z.enum(['Confirmed','Cancelled']).parse(req.body.status);const result=status==='Cancelled'?await Consultation.findByIdAndDelete(id.parse(req.params.id)):await Consultation.findByIdAndUpdate(id.parse(req.params.id),{status});if(!result)throw fail('Not found',404);res.json({data:true});});
app.get('/api/notifications',auth,async(req:any,res)=>res.json({data:await Notification.find({user:req.user._id}).sort({createdAt:-1}).limit(100)}));
app.get('/api/tasks',auth,async(req:any,res)=>{let filter:any={};if(req.user.role==='Customer')throw fail('Access denied',403);if(req.user.role==='Staff')filter={assignedTo:req.user._id};else if(req.user.role!=='Super Admin')filter={venue:{$in:req.user.venues}};res.json({data:await Task.find(filter).sort({createdAt:-1}).limit(100)});});
app.post('/api/tasks',roles('Super Admin','Branch Admin','Hall Manager'),async(req:any,res)=>{const input=z.object({booking:id,title:z.string().min(3).max(200),assignedTo:id}).parse(req.body);const b=await Booking.findOne({_id:input.booking,...scope(req.user)});if(!b)throw fail('Booking not found',404);if(!await User.exists({_id:input.assignedTo,role:{$in:['Staff','Hall Manager']},venues:b.venue}))throw fail('Assignee unavailable');const task=await Task.create({...input,venue:b.venue});await Notification.create({user:input.assignedTo,message:'New task: '+input.title});res.status(201).json({data:task});});
app.patch('/api/tasks/:id',auth,async(req:any,res)=>{if(req.user.role==='Customer')throw fail('Access denied',403);const filter:any={_id:id.parse(req.params.id)};if(req.user.role==='Staff')filter.assignedTo=req.user._id;else if(req.user.role!=='Super Admin')filter.venue={$in:req.user.venues};const result=await Task.findOneAndUpdate(filter,{status:z.enum(['To Do','In Progress','Done']).parse(req.body.status)});if(!result)throw fail('Task not found',404);res.json({data:true});});
app.get('/api/admin/users',finance,async(_req,res)=>res.json({data:await User.find().select('name email role venues').sort({name:1}).limit(100)}));
app.patch('/api/admin/users/:id',finance,async(req:any,res)=>{const input=z.object({role:z.enum(['Customer','Branch Admin','Hall Manager','Staff']),venues:z.array(id).max(100)}).parse(req.body);if(req.params.id===String(req.user._id))throw fail('Cannot change own role');await User.findOneAndUpdate({_id:id.parse(req.params.id),role:{$ne:'Super Admin'}},input);await Session.deleteMany({user:req.params.id});await audit(req,'user.permissions',req.params.id);res.json({data:true});});
const venueInput=z.object({name:z.string().min(3).max(100),city:z.string().min(2).max(100),capacity:z.number().int().min(1).max(5000),rental:z.number().int().nonnegative().max(1000000000),outdoor:z.boolean(),description:z.string().min(10).max(3000),amenities:z.array(z.string().max(100)).max(30),image:z.url().refine(s=>s.startsWith('https://')),taxBps:z.number().int().min(0).max(10000),archived:z.boolean().default(false)});
const packInput=z.object({name:z.string().min(3).max(100),perHead:z.number().int().nonnegative().max(10000000),decor:z.number().int().nonnegative().max(1000000000),minGuests:z.number().int().min(1),maxGuests:z.number().int().min(1).max(5000),inclusions:z.array(z.string().max(100)).max(30),archived:z.boolean().default(false)}).refine(p=>p.minGuests<=p.maxGuests);
for(const [path,Model,validator] of [['venues',Venue,venueInput],['packages',Package,packInput]] as const){app.post('/api/admin/'+path,finance,async(req:any,res)=>{const record=await (Model as any).create(validator.parse(req.body) as any);await audit(req,path+'.create',String(record._id));res.status(201).json({data:record});});app.put('/api/admin/'+path+'/:id',finance,async(req:any,res)=>{const record=await (Model as any).findByIdAndUpdate(id.parse(req.params.id),validator.parse(req.body),{new:true,runValidators:true});if(!record)throw fail('Not found',404);await audit(req,path+'.edit',String(record._id));res.json({data:record});});}
app.post('/api/admin/maintenance',admins,async(req:any,res)=>{const b=z.object({venue:id,date,slot}).parse(req.body);if(req.user.role!=='Super Admin'&&!req.user.venues.some((v:any)=>String(v)===b.venue))throw fail('Access denied',403);res.status(201).json({data:await Reservation.create({...b,maintenance:true})});});
app.get('/api/expenses',finance,async(_req,res)=>res.json({data:await Expense.find().sort({createdAt:-1}).limit(100)}));
app.post('/api/expenses',finance,async(req:any,res)=>{const b=z.object({amount:z.number().int().positive(),category:z.string().min(2).max(100),description:z.string().min(3).max(500),key:z.string().uuid()}).parse(req.body);res.status(201).json({data:await Expense.findOneAndUpdate({key:b.key},{$setOnInsert:{...b,actor:req.user._id}},{upsert:true,new:true})});});
app.get('/api/audit',finance,async(_req,res)=>res.json({data:await Audit.find().sort({createdAt:-1}).limit(100)}));
app.get('/api/reports',finance,async(req,res)=>{const from=date.parse(req.query.from),to=date.parse(req.query.to);if(from>to)throw fail('Invalid range');const range={createdAt:{$gte:new Date(from),$lt:new Date(new Date(to).getTime()+86400000)}};const [entries,expenses,bookings]=await Promise.all([Ledger.find(range),Expense.find(range),Booking.find({date:{$gte:from,$lte:to},status:{$ne:'Cancelled'}})]);const collections=entries.reduce((n,e)=>n+e.amount!,0),costs=expenses.reduce((n,e)=>n+e.amount!,0);res.json({data:{from,to,netCollections:collections,expenses:costs,bookedInvoiceTotal:bookings.reduce((n,b)=>n+b.snapshot.total,0),receivables:bookings.reduce((n,b)=>n+b.snapshot.total-b.paid!,0),bookings:bookings.length,cashLessExpenses:collections-costs,definitions:'Collections by ledger posting date; bookings and receivables by event date. Cash less expenses is not recognized profit.'}});});
app.get('/api/reports/export',finance,async(_req,res)=>{const rows=await Ledger.find().sort({createdAt:1}).limit(10000);res.type('text/csv').attachment('royalvows-ledger.csv').send('date,booking,type,amount_minor\n'+rows.map((r:any)=>[r.createdAt.toISOString(),r.booking,r.type,r.amount].join(',')).join('\n'));});
operations(app,auth,roles);integrations(app,auth,roles,loginLimit);app.use((_req,_res,next)=>next(fail('Endpoint not found',404)));app.use((error:any,_req:any,res:any,_next:any)=>{const status=error instanceof z.ZodError?400:error.code===11000?409:error.status||500;res.status(status).json({error:{message:status===500?'Service unavailable. Please retry.':error.code===11000?'This slot or record is already reserved':error instanceof z.ZodError?error.issues.map((i:any)=>i.message).join('; '):error.message}});});
await mongoose.connect(env.MONGODB_URI);await Promise.all(mongoose.modelNames().map(name=>mongoose.model(name).init()));app.listen(env.PORT,'127.0.0.1',()=>console.log('RoyalVows API on port '+env.PORT));
